#!/usr/bin/env bash
#A loop that repeat echo 10 times
counter=1
while [ "$counter" -le 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo -e "Best School\nHi"
		((counter++))		
	else
		echo Best School
		((counter++))
	fi	
done
