#!/usr/bin/env bash
#A loop that repeat echo 10 times
counter=1
while [ "$counter" -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo bad luck
		((counter++))		
	elif [ "$counter" -eq 8 ]
	then
		echo good luck
		((counter++))
	else
		echo Best School
		((counter++))
	fi	
done
