#!/usr/bin/env bash
#A loop that repeat echo 10 times
counter=1
while [ "$counter" -le 20 ]
do
	case $counter in
	4) echo -e "$counter\nbad luck from China"
		((counter++));;
	9) echo -e "$counter\nbad luck from Japan"
		((counter++));;
	17) echo -e "$counter\nbad luck from Italy"
		((counter++));;
	*) echo $counter
		((counter++));;
	esac
done
