#!/usr/bin/env bash
#This script will display its own PID
deletefileandexit(){
rm -f /var/run/myscript.pid;
exit
}

trap "echo 'Y U no love me?!' deletefileandexit" SIGINT
trap "echo 'I hate the kill command'; deletefileandexit" SIGTERM
trap "echo 'I hate the kill command'; deletefileandexit" SIGQUIT

echo $$ >> /var/run/myscript.pid
while : ; do
	echo "To infinity and beyond"
	sleep 2
done
