#!/usr/bin/env bash
#This script will display its own PID
PIDFILE=/var/run/my_process.pid
if [ "${1}" == "start" ] ; then
	./manage_my_process &
	touch "$PIDFILE"
	echo "$!" > "$PIDFILE"
	echo "manage_my_process started"
elif [ "${1}" == "stop" ] ; then
	echo "manage_my_process stopped"
	kill "$($PIDFILE)"
	rm "$PIDFILE"
elif [ "${1}" == "restart" ] ; then
	kill "$($PIDFILE)"
	rm "$PIDFILE"
	./manage_my_process.pid
	echo "$!" > "$PDIFILE"
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
